# Generated by Django 3.1.7 on 2021-11-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20211029_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(default='https://res.cloudinary.com/job-search-agency/image/upload/v1635868698/images/companyLogo_lkfk3t.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='profile_pic',
            field=models.ImageField(default='https://res.cloudinary.com/job-search-agency/image/upload/v1635866409/images/default_jrmwis.png', upload_to='images/'),
        ),
    ]
