# Generated by Django 3.1.7 on 2021-11-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20211102_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
