# Generated by Django 3.1.7 on 2021-11-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20211102_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
