# Generated by Django 3.1.7 on 2021-11-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20211106_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='profession',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
