# Generated by Django 3.1.7 on 2021-11-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='worktype',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default=2, max_length=500),
            preserve_default=False,
        ),
    ]
