# Generated by Django 3.1.7 on 2021-11-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20211106_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Subscribed time')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='jobtitle',
            field=models.CharField(max_length=500, verbose_name='Job title'),
        ),
    ]
