# Generated by Django 3.1.7 on 2021-11-15 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20211115_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='', verbose_name='Cv')),
                ('coverletter', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Cover Letter')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Subscribed time')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.employee')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
