# Generated by Django 3.1.7 on 2021-11-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_application_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Applied time'),
        ),
    ]
