# Generated by Django 3.1.7 on 2021-11-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20211117_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='job_id',
        ),
    ]
