# Generated by Django 3.1.7 on 2021-11-17 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_remove_application_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cv',
        ),
        migrations.AddField(
            model_name='application',
            name='job_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
            preserve_default=False,
        ),
    ]
