# Generated by Django 3.1.7 on 2021-11-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_auto_20211117_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='behance',
        ),
        migrations.RemoveField(
            model_name='social',
            name='url',
        ),
        migrations.AddField(
            model_name='social',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='social',
            name='instagram',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='social',
            name='youtube',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='social',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
