# Generated by Django 3.1.7 on 2021-11-17 20:13

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_auto_20211117_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Social', 'verbose_name_plural': 'Socials'},
        ),
        migrations.AlterField(
            model_name='about',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='profile_pic',
            field=models.ImageField(upload_to='images/', verbose_name='Profile image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='ip',
            field=models.CharField(blank=True, max_length=20, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='message',
            field=models.TextField(blank=True, max_length=555, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Read', 'Read')], default='New', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(max_length=350, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='addressUrl',
            field=models.URLField(blank=True, max_length=1200, verbose_name='Address url'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phonenumber',
            field=models.PositiveIntegerField(blank=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=200, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profession',
            field=models.CharField(blank=True, max_length=200, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(default='images/default.png', upload_to='images/', verbose_name='Profile image'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='city',
            field=models.CharField(blank=True, max_length=200, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(upload_to='images/', verbose_name='Company logo'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='companyinfo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Company information'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='companyname',
            field=models.CharField(max_length=200, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='mobilenumber',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mobile number'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=200, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='profile_pic',
            field=models.ImageField(upload_to='images/', verbose_name='Profile image'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.CharField(blank=True, max_length=200, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='job',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.employer', verbose_name='Employer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('Not requested', 'Not requested'), ('Experience > 1', 'Experience > 1'), ('Experience > 3', 'Experience > 3'), ('Experience > 5', 'Experience > 5')], max_length=500, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcategory', verbose_name='Job category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('Not requested', 'Not requested'), ('Bachelor degre', 'Bachelor degre'), ('Master degree', 'Master degree'), ('PHD degree', 'PHD degree')], max_length=500, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='job',
            name='overview',
            field=models.CharField(max_length=2000, verbose_name='Overview'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.PositiveIntegerField(verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('Contract', 'Contract'), ('Internship', 'Internship'), ('Part time', 'Part time')], max_length=500, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='worktype',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=500, verbose_name='Work type'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='title',
            field=models.CharField(max_length=1250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='jobs.Category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=models.TextField(verbose_name='Overview'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='jobs.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='View count'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='social',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='social',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.URLField(blank=True, max_length=500, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='social',
            name='instagram',
            field=models.URLField(blank=True, max_length=500, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='social',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter',
            field=models.URLField(blank=True, max_length=500, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='social',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='social',
            name='youtube',
            field=models.URLField(blank=True, max_length=500, verbose_name='Youtube'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='team',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fullname'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='team',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='term',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='term',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='term',
            name='title',
            field=models.CharField(max_length=3000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='term',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profession',
            field=models.CharField(blank=True, max_length=200, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
    ]
