# Generated by Django 3.1.7 on 2021-11-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(default=2, upload_to='', verbose_name='Cv'),
            preserve_default=False,
        ),
    ]
