# Generated by Django 3.1.7 on 2021-12-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_application_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(upload_to='images/', verbose_name='Profile image'),
        ),
    ]
